//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ui.rc
//
#define IDI_PLUGIN                      101
#define IDB_CHECKS                      102
#define IDD_DISPLAYS                    103
#define IDD_GENERAL                     104
#define IDD_DISPLAY                     105
#define IDD_KEYPAD                      106
#define IDD_KEYPAD_ENTRY                107
#define IDD_FANS                        108
#define IDD_FAN                         109
#define IDD_SENSORS                     110
#define IDD_SENSOR                      111
#define IDD_COMMAND                     112
#define IDS_NEW_DEVICE_NAME             101
#define IDS_NAME                        102
#define IDS_DEVICE                      103
#define IDS_BACKLIGHT                   104
#define IDS_BRIGHTNESS                  105
#define IDS_INPUT                       106
#define IDS_EVENT                       107
#define IDS_NEW_FAN_NAME                108
#define IDS_FAN                         109
#define IDS_RPM                         110
#define IDS_NEW_SENSOR_NAME             111
#define IDS_ROM                         112
#define IDS_TEMPERATURE                 113
#define IDS_VARIABLE                    114
#define IDS_VALUE                       115
#define IDS_BUTTON                      116
#define IDS_LEGEND                      117
#define IDS_GPOL                        118
#define IDS_FANL                        119
#define IDC_APPLY                       1000
#define IDC_DISPLAYS                    1001
#define IDC_ADD                         1002
#define IDC_EDIT                        1003
#define IDC_REMOVE                      1004
#define IDC_DEFAULT                     1005
#define IDC_NAMEL                       1006
#define IDC_NAME                        1007
#define IDC_ENABLED                     1008
#define IDC_DEVICEL                     1009
#define IDC_DEVICE                      1010
#define IDC_ROWL                        1011
#define IDC_ROW                         1012
#define IDC_ROW_SPIN                    1013
#define IDC_COLL                        1014
#define IDC_COL                         1015
#define IDC_COL_SPIN                    1016
#define IDC_PORTL                       1017
#define IDC_PORT                        1018
#define IDC_SPEEDL                      1019
#define IDC_SPEED                       1020
#define IDC_CONTRASTL                   1021
#define IDC_CONTRAST                    1022
#define IDC_BRIGHTNESS                  1023
#define IDC_BRIGHTNESSL                 1024
#define IDC_TEST                        1025
#define IDC_ENTRIES                     1026
#define IDC_RESET                       1027
#define IDC_PASSTHRU                    1028
#define IDC_INPUT                       1029
#define IDC_EVENT                       1030
#define IDC_FANS                        1031
#define IDC_REFRESH                     1032
#define IDC_INTERVALL                   1033
#define IDC_INTERVAL                    1034
#define IDC_INTERVALL2                  1035
#define IDC_PPR                         1036
#define IDC_PPR_SPIN                    1037
#define IDC_SENSORS                     1038
#define IDC_DISPLAYL                    1039
#define IDC_DISPLAY                     1040
#define IDC_TYPEL                       1041
#define IDC_TYPE                        1042
#define IDC_VALUEL                      1043
#define IDC_VALSTR                      1044
#define IDC_VALLIST                     1045
#define IDC_VALINT                      1046
#define IDC_VAL_SPIN                    1047
#define IDC_VALBOOL                     1048
#define IDC_USE_WRAP                    1049
#define IDC_USE_COL                     1050
#define IDC_USE_REST                    1051
#define IDC_USE_WIDTH                   1052
#define IDC_WIDTH                       1053
#define IDC_WIDTH_SPIN                  1054
#define IDC_SCREENL                     1055
#define IDC_ENABLE_LINE1                1056
#define IDC_ENABLE_LINE2                1057
#define IDC_ENABLE_LINE3                1058
#define IDC_ENABLE_LINE4                1059
#define IDC_LINE1                       1060
#define IDC_LINE2                       1061
#define IDC_LINE3                       1062
#define IDC_LINE4                       1063
#define IDC_MARQUEE_LINE1               1064
#define IDC_MARQUEE_LINE2               1065
#define IDC_MARQUEE_LINE3               1066
#define IDC_MARQUEE_LINE4               1067
#define IDC_VALUE2L                     1068
#define IDC_VALSTR2                     1069
#define IDC_VALLIST2                    1070
#define IDC_FANGPO                      1071
#define IDC_FANGPO_SPIN                 1072

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        113
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1073
#define _APS_NEXT_SYMED_VALUE           120
#endif
#endif
