<?xml version="1.0" encoding="UTF-8"?>
<!-- $Header$ -->
<Girder>
  <Group Name="Commands" Identifier="1" Enabled="TRUE">
    <Comments>Test each command type</Comments>
    <Command Name="String" Identifier="2" Enabled="TRUE">
      <Comments>Display string</Comments>
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <OSD>FALSE</OSD>
      <Submatch>FALSE</Submatch>
      <Topmost>TRUE</Topmost>
      <OneMatch>FALSE</OneMatch>
      <UseVar>FALSE</UseVar>
      <MatchHidden>FALSE</MatchHidden>
      <MatchNum>1</MatchNum>
      <ActionType>118</ActionType>
      <ActionSubType>1</ActionSubType>
      <sValue1>0123456789</sValue1>
      <sValue2>s</sValue2>
      <iValue1>1</iValue1>
      <iValue3>10</iValue3>
      <bValue1>FALSE</bValue1>
      <bValue2>FALSE</bValue2>
      <bValue3>FALSE</bValue3>
    </Command>
    <Command Name="Variable" Identifier="3" Enabled="TRUE">
      <Comments>Display variable value</Comments>
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <OSD>FALSE</OSD>
      <Submatch>FALSE</Submatch>
      <Topmost>TRUE</Topmost>
      <OneMatch>FALSE</OneMatch>
      <UseVar>FALSE</UseVar>
      <MatchHidden>FALSE</MatchHidden>
      <MatchNum>1</MatchNum>
      <ActionType>118</ActionType>
      <ActionSubType>1</ActionSubType>
      <sValue1>PI</sValue1>
      <sValue2>v</sValue2>
      <iValue3>4</iValue3>
      <bValue1>FALSE</bValue1>
      <bValue2>FALSE</bValue2>
      <bValue3>FALSE</bValue3>
    </Command>
    <Command Name="Date / Time" Identifier="4" Enabled="TRUE">
      <Comments>Display current date</Comments>
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <OSD>FALSE</OSD>
      <Submatch>FALSE</Submatch>
      <Topmost>TRUE</Topmost>
      <OneMatch>FALSE</OneMatch>
      <UseVar>FALSE</UseVar>
      <MatchHidden>FALSE</MatchHidden>
      <MatchNum>1</MatchNum>
      <ActionType>118</ActionType>
      <ActionSubType>1</ActionSubType>
      <sValue1>%Y-%m-%d %H:%M:%S</sValue1>
      <sValue2>t</sValue2>
      <iValue3>-1</iValue3>
      <bValue1>FALSE</bValue1>
      <bValue2>FALSE</bValue2>
      <bValue3>FALSE</bValue3>
    </Command>
    <MultiGroup Name="Filename" Identifier="5" Enabled="TRUE">
      <Comments>Display trimmed filename</Comments>
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <Command Name="Variable" Identifier="6" Enabled="TRUE">
        <Comments>Compose filename</Comments>
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <Binary Encoding="Base64">G0x1YUABBAQEIAYJCBLmW6GwubJBCAAAAD0obm9uZSkAAAAAAAAAAAAAAgAAAAAAAAAAAAAABAAA
AAkAAABGaWxlTmFtZQANAAAAR2V0RGlyZWN0b3J5AAoAAABHSVJERVJESVIADAAAAFxnaXJkZXIu
ZXhlAAAAAAAAAAAABwAAAEwAAACHAAAAQgAAAMcAAACdAAAAEwAAAAAAAAA=</Binary>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>4</ActionType>
        <ActionSubType>34</ActionSubType>
        <sValue1>FileName = GetDirectory("GIRDERDIR") .. "\\girder.exe"
</sValue1>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="Display" Identifier="7" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>FileName</sValue1>
        <sValue2>f</sValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
    </MultiGroup>
    <Command Name="Close" Identifier="8" Enabled="TRUE">
      <Comments>Close display</Comments>
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <OSD>FALSE</OSD>
      <Submatch>FALSE</Submatch>
      <Topmost>TRUE</Topmost>
      <OneMatch>FALSE</OneMatch>
      <UseVar>FALSE</UseVar>
      <MatchHidden>FALSE</MatchHidden>
      <MatchNum>1</MatchNum>
      <ActionType>118</ActionType>
      <ActionSubType>1</ActionSubType>
      <sValue2>x</sValue2>
      <iValue3>-1</iValue3>
      <bValue1>FALSE</bValue1>
      <bValue2>FALSE</bValue2>
      <bValue3>FALSE</bValue3>
    </Command>
    <Command Name="Clear" Identifier="9" Enabled="TRUE">
      <Comments>Clear display</Comments>
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <OSD>FALSE</OSD>
      <Submatch>FALSE</Submatch>
      <Topmost>TRUE</Topmost>
      <OneMatch>FALSE</OneMatch>
      <UseVar>FALSE</UseVar>
      <MatchHidden>FALSE</MatchHidden>
      <MatchNum>1</MatchNum>
      <ActionType>118</ActionType>
      <ActionSubType>1</ActionSubType>
      <sValue2>c</sValue2>
      <iValue3>-1</iValue3>
      <bValue1>FALSE</bValue1>
      <bValue2>FALSE</bValue2>
      <bValue3>FALSE</bValue3>
    </Command>
    <Command Name="Screen" Identifier="10" Enabled="TRUE">
      <Comments>Multi-line screen w/ variable &amp; marquee</Comments>
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <OSD>FALSE</OSD>
      <Submatch>FALSE</Submatch>
      <Topmost>TRUE</Topmost>
      <OneMatch>FALSE</OneMatch>
      <UseVar>FALSE</UseVar>
      <MatchHidden>FALSE</MatchHidden>
      <MatchNum>1</MatchNum>
      <ActionType>118</ActionType>
      <ActionSubType>1</ActionSubType>
      <sValue1>[_VERSION]
abcdefghijklmnopqrstuvwxyz

</sValue1>
      <sValue2>#</sValue2>
      <iValue1>12</iValue1>
      <iValue2>2</iValue2>
      <iValue3>-1</iValue3>
      <bValue1>FALSE</bValue1>
      <bValue2>FALSE</bValue2>
      <bValue3>FALSE</bValue3>
    </Command>
    <Command Name="Character" Identifier="11" Enabled="TRUE">
      <Comments>Character by code</Comments>
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <OSD>FALSE</OSD>
      <Submatch>FALSE</Submatch>
      <Topmost>TRUE</Topmost>
      <OneMatch>FALSE</OneMatch>
      <UseVar>FALSE</UseVar>
      <MatchHidden>FALSE</MatchHidden>
      <MatchNum>1</MatchNum>
      <ActionType>118</ActionType>
      <ActionSubType>1</ActionSubType>
      <sValue1>42</sValue1>
      <sValue2>*</sValue2>
      <iValue1>1</iValue1>
      <iValue2>1</iValue2>
      <iValue3>1</iValue3>
      <bValue1>FALSE</bValue1>
      <bValue2>FALSE</bValue2>
      <bValue3>FALSE</bValue3>
    </Command>
    <Command Name="Custom Char" Identifier="12" Enabled="TRUE">
      <Comments>Custom character (NE arrow)</Comments>
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <OSD>FALSE</OSD>
      <Submatch>FALSE</Submatch>
      <Topmost>TRUE</Topmost>
      <OneMatch>FALSE</OneMatch>
      <UseVar>FALSE</UseVar>
      <MatchHidden>FALSE</MatchHidden>
      <MatchNum>1</MatchNum>
      <ActionType>118</ActionType>
      <ActionSubType>1</ActionSubType>
      <sValue1>0b01111 0b00011 0b00101 0b01000</sValue1>
      <sValue2>$</sValue2>
      <iValue1>1</iValue1>
      <iValue2>2</iValue2>
      <iValue3>1</iValue3>
      <bValue1>FALSE</bValue1>
      <bValue2>FALSE</bValue2>
      <bValue3>FALSE</bValue3>
    </Command>
    <Command Name="GPO" Identifier="13" Enabled="TRUE">
      <Comments>General purpose output</Comments>
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <OSD>FALSE</OSD>
      <Submatch>FALSE</Submatch>
      <Topmost>TRUE</Topmost>
      <OneMatch>FALSE</OneMatch>
      <UseVar>FALSE</UseVar>
      <MatchHidden>FALSE</MatchHidden>
      <MatchNum>1</MatchNum>
      <ActionType>118</ActionType>
      <ActionSubType>1</ActionSubType>
      <sValue2>o</sValue2>
      <iValue1>1</iValue1>
      <iValue3>-1</iValue3>
      <bValue1>TRUE</bValue1>
      <bValue2>FALSE</bValue2>
      <bValue3>FALSE</bValue3>
    </Command>
  </Group>
  <Group Name="Custom" Identifier="14" Enabled="TRUE">
    <Comments>Test custom characters</Comments>
    <MultiGroup Name="00-0F" Identifier="15" Enabled="TRUE">
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <Command Name="Legend" Identifier="16" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>01234567</sValue1>
        <sValue2>s</sValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="00" Identifier="17" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>
0b00010
0b00100
0b01000
0b01000
0b01000
0b00100
0b00010
0b11111
</sValue1>
        <sValue2>$</sValue2>
        <iValue1>1</iValue1>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="01" Identifier="18" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>
0b01110
0b10001
0b10000
0b10000
0b10000
0b10001
0b01110
0b11111
</sValue1>
        <sValue2>$</sValue2>
        <iValue1>1</iValue1>
        <iValue2>1</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="02" Identifier="19" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>
0b10001
0b10001
0b10001
0b10001
0b10001
0b10001
0b01110
0b11111
</sValue1>
        <sValue2>$</sValue2>
        <iValue1>1</iValue1>
        <iValue2>2</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="03" Identifier="20" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>
0b01111
0b10000
0b10000
0b01110
0b00001
0b00001
0b11110
0b11111
</sValue1>
        <sValue2>$</sValue2>
        <iValue1>1</iValue1>
        <iValue2>3</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="04" Identifier="21" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>
0b11111
0b00100
0b00100
0b00100
0b00100
0b00100
0b00100
0b11111
</sValue1>
        <sValue2>$</sValue2>
        <iValue1>1</iValue1>
        <iValue2>4</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="05" Identifier="22" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>
0b01110
0b10001
0b10001
0b10001
0b10001
0b10001
0b01110
0b11111
</sValue1>
        <sValue2>$</sValue2>
        <iValue1>1</iValue1>
        <iValue2>5</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="06" Identifier="23" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>
0b10001
0b11011
0b10101
0b10101
0b10001
0b10001
0b10001
0b11111
</sValue1>
        <sValue2>$</sValue2>
        <iValue1>1</iValue1>
        <iValue2>6</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="07" Identifier="24" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>
0b01000
0b00100
0b00010
0b00010
0b00010
0b00100
0b01000
0b11111
</sValue1>
        <sValue2>$</sValue2>
        <iValue1>1</iValue1>
        <iValue2>7</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
    </MultiGroup>
  </Group>
  <Group Name="All Chars" Identifier="25" Enabled="TRUE">
    <Comments>Test every possible character code</Comments>
    <MultiGroup Name="00-0F" Identifier="26" Enabled="TRUE">
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <Command Name="Legend" Identifier="27" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0123456789ABCDEF  0</sValue1>
        <sValue2>s</sValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="00" Identifier="28" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x00</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="01" Identifier="29" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x01</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>1</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="02" Identifier="30" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x02</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>2</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="03" Identifier="31" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x03</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>3</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="04" Identifier="32" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x04</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>4</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="05" Identifier="33" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x05</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>5</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="06" Identifier="34" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x06</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>6</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="07" Identifier="35" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x07</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>7</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="08" Identifier="36" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x08</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>8</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="09" Identifier="37" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x09</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>9</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="0A" Identifier="38" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x0A</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>10</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="0B" Identifier="39" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x0B</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>11</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="0C" Identifier="40" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x0C</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>12</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="0D" Identifier="41" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x0D</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>13</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="0E" Identifier="42" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x0E</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>14</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="0F" Identifier="43" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x0F</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>15</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
    </MultiGroup>
    <MultiGroup Name="10-1F" Identifier="44" Enabled="TRUE">
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <Command Name="Legend" Identifier="45" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0123456789ABCDEF  1</sValue1>
        <sValue2>s</sValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="10" Identifier="46" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x10</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="11" Identifier="47" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x11</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>1</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="12" Identifier="48" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x12</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>2</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="13" Identifier="49" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x13</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>3</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="14" Identifier="50" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x14</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>4</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="15" Identifier="51" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x15</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>5</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="16" Identifier="52" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x16</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>6</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="17" Identifier="53" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x17</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>7</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="18" Identifier="54" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x18</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>8</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="19" Identifier="55" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x19</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>9</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="1A" Identifier="56" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x1A</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>10</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="1B" Identifier="57" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x1B</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>11</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="1C" Identifier="58" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x1C</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>12</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="1D" Identifier="59" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x1D</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>13</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="1E" Identifier="60" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x1E</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>14</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="1F" Identifier="61" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x1F</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>15</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
    </MultiGroup>
    <Command Name="20-2F" Identifier="62" Enabled="TRUE">
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <OSD>FALSE</OSD>
      <Submatch>FALSE</Submatch>
      <Topmost>TRUE</Topmost>
      <OneMatch>FALSE</OneMatch>
      <UseVar>FALSE</UseVar>
      <MatchHidden>FALSE</MatchHidden>
      <MatchNum>1</MatchNum>
      <ActionType>118</ActionType>
      <ActionSubType>1</ActionSubType>
      <sValue1>0123456789ABCDEF  2
 !"#$%&amp;'()*+,-./</sValue1>
      <sValue2>#</sValue2>
      <iValue3>-1</iValue3>
      <bValue1>FALSE</bValue1>
      <bValue2>FALSE</bValue2>
      <bValue3>FALSE</bValue3>
    </Command>
    <Command Name="30-3F" Identifier="63" Enabled="TRUE">
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <OSD>FALSE</OSD>
      <Submatch>FALSE</Submatch>
      <Topmost>TRUE</Topmost>
      <OneMatch>FALSE</OneMatch>
      <UseVar>FALSE</UseVar>
      <MatchHidden>FALSE</MatchHidden>
      <MatchNum>1</MatchNum>
      <ActionType>118</ActionType>
      <ActionSubType>1</ActionSubType>
      <sValue1>0123456789ABCDEF  3
0123456789:;&lt;=&gt;?</sValue1>
      <sValue2>#</sValue2>
      <iValue3>-1</iValue3>
      <bValue1>FALSE</bValue1>
      <bValue2>FALSE</bValue2>
      <bValue3>FALSE</bValue3>
    </Command>
    <Command Name="40-4F" Identifier="64" Enabled="TRUE">
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <OSD>FALSE</OSD>
      <Submatch>FALSE</Submatch>
      <Topmost>TRUE</Topmost>
      <OneMatch>FALSE</OneMatch>
      <UseVar>FALSE</UseVar>
      <MatchHidden>FALSE</MatchHidden>
      <MatchNum>1</MatchNum>
      <ActionType>118</ActionType>
      <ActionSubType>1</ActionSubType>
      <sValue1>0123456789ABCDEF  4
@ABCDEFGHIJKLMNO</sValue1>
      <sValue2>#</sValue2>
      <iValue3>-1</iValue3>
      <bValue1>FALSE</bValue1>
      <bValue2>FALSE</bValue2>
      <bValue3>FALSE</bValue3>
    </Command>
    <Command Name="50-5F" Identifier="65" Enabled="TRUE">
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <OSD>FALSE</OSD>
      <Submatch>FALSE</Submatch>
      <Topmost>TRUE</Topmost>
      <OneMatch>FALSE</OneMatch>
      <UseVar>FALSE</UseVar>
      <MatchHidden>FALSE</MatchHidden>
      <MatchNum>1</MatchNum>
      <ActionType>118</ActionType>
      <ActionSubType>1</ActionSubType>
      <sValue1>0123456789ABCDEF  5
PQRSTUVWXYZ[[\]^_</sValue1>
      <sValue2>#</sValue2>
      <iValue3>-1</iValue3>
      <bValue1>FALSE</bValue1>
      <bValue2>FALSE</bValue2>
      <bValue3>FALSE</bValue3>
    </Command>
    <Command Name="60-6F" Identifier="66" Enabled="TRUE">
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <OSD>FALSE</OSD>
      <Submatch>FALSE</Submatch>
      <Topmost>TRUE</Topmost>
      <OneMatch>FALSE</OneMatch>
      <UseVar>FALSE</UseVar>
      <MatchHidden>FALSE</MatchHidden>
      <MatchNum>1</MatchNum>
      <ActionType>118</ActionType>
      <ActionSubType>1</ActionSubType>
      <sValue1>0123456789ABCDEF  6
`abcdefghijklmno</sValue1>
      <sValue2>#</sValue2>
      <iValue3>-1</iValue3>
      <bValue1>FALSE</bValue1>
      <bValue2>FALSE</bValue2>
      <bValue3>FALSE</bValue3>
    </Command>
    <MultiGroup Name="70-7F" Identifier="67" Enabled="TRUE">
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <Command Name="70-7E" Identifier="68" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0123456789ABCDEF  7
pqrstuvwxyz{|}~</sValue1>
        <sValue2>#</sValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="7F" Identifier="69" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x7F</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>15</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
    </MultiGroup>
    <MultiGroup Name="80-8F" Identifier="70" Enabled="TRUE">
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <Command Name="Legend" Identifier="71" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0123456789ABCDEF  0</sValue1>
        <sValue2>s</sValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="80" Identifier="72" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x80</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="81" Identifier="73" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x81</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>1</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="82" Identifier="74" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x82</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>2</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="83" Identifier="75" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x83</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>3</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="84" Identifier="76" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x84</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>4</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="85" Identifier="77" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x85</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>5</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="86" Identifier="78" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x86</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>6</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="87" Identifier="79" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x87</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>7</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="88" Identifier="80" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x88</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>8</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="89" Identifier="81" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x89</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>9</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="8A" Identifier="82" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x8A</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>10</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="8B" Identifier="83" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x8B</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>11</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="8C" Identifier="84" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x8C</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>12</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="8D" Identifier="85" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x8D</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>13</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="8E" Identifier="86" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x8E</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>14</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="8F" Identifier="87" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x8F</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>15</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
    </MultiGroup>
    <MultiGroup Name="90-9F" Identifier="88" Enabled="TRUE">
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <Command Name="Legend" Identifier="89" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0123456789ABCDEF  0</sValue1>
        <sValue2>s</sValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="90" Identifier="90" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x90</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="91" Identifier="91" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x91</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>1</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="92" Identifier="92" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x92</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>2</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="93" Identifier="93" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x93</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>3</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="94" Identifier="94" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x94</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>4</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="95" Identifier="95" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x95</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>5</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="96" Identifier="96" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x96</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>6</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="97" Identifier="97" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x97</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>7</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="98" Identifier="98" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x98</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>8</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="99" Identifier="99" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x99</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>9</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="9A" Identifier="100" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x9A</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>10</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="9B" Identifier="101" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x9B</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>11</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="9C" Identifier="102" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x9C</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>12</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="9D" Identifier="103" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x9D</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>13</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="9E" Identifier="104" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x9E</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>14</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="9F" Identifier="105" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x9F</sValue1>
        <sValue2>*</sValue2>
        <iValue1>1</iValue1>
        <iValue2>15</iValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
    </MultiGroup>
    <Command Name="A0-AF" Identifier="106" Enabled="TRUE">
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <OSD>FALSE</OSD>
      <Submatch>FALSE</Submatch>
      <Topmost>TRUE</Topmost>
      <OneMatch>FALSE</OneMatch>
      <UseVar>FALSE</UseVar>
      <MatchHidden>FALSE</MatchHidden>
      <MatchNum>1</MatchNum>
      <ActionType>118</ActionType>
      <ActionSubType>1</ActionSubType>
      <sValue1>0123456789ABCDEF  A
 ¡¢£¤¥¦§¨©ª«¬­®¯</sValue1>
      <sValue2>#</sValue2>
      <iValue3>-1</iValue3>
      <bValue1>FALSE</bValue1>
      <bValue2>FALSE</bValue2>
      <bValue3>FALSE</bValue3>
    </Command>
    <Command Name="B0-BF" Identifier="107" Enabled="TRUE">
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <OSD>FALSE</OSD>
      <Submatch>FALSE</Submatch>
      <Topmost>TRUE</Topmost>
      <OneMatch>FALSE</OneMatch>
      <UseVar>FALSE</UseVar>
      <MatchHidden>FALSE</MatchHidden>
      <MatchNum>1</MatchNum>
      <ActionType>118</ActionType>
      <ActionSubType>1</ActionSubType>
      <sValue1>0123456789ABCDEF  B
°±²³´µ¶·¸¹º»¼½¾¿</sValue1>
      <sValue2>#</sValue2>
      <iValue3>-1</iValue3>
      <bValue1>FALSE</bValue1>
      <bValue2>FALSE</bValue2>
      <bValue3>FALSE</bValue3>
    </Command>
    <Command Name="C0-CF" Identifier="108" Enabled="TRUE">
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <OSD>FALSE</OSD>
      <Submatch>FALSE</Submatch>
      <Topmost>TRUE</Topmost>
      <OneMatch>FALSE</OneMatch>
      <UseVar>FALSE</UseVar>
      <MatchHidden>FALSE</MatchHidden>
      <MatchNum>1</MatchNum>
      <ActionType>118</ActionType>
      <ActionSubType>1</ActionSubType>
      <sValue1>0123456789ABCDEF  C
ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏ</sValue1>
      <sValue2>#</sValue2>
      <iValue3>-1</iValue3>
      <bValue1>FALSE</bValue1>
      <bValue2>FALSE</bValue2>
      <bValue3>FALSE</bValue3>
    </Command>
    <Command Name="D0-DF" Identifier="109" Enabled="TRUE">
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <OSD>FALSE</OSD>
      <Submatch>FALSE</Submatch>
      <Topmost>TRUE</Topmost>
      <OneMatch>FALSE</OneMatch>
      <UseVar>FALSE</UseVar>
      <MatchHidden>FALSE</MatchHidden>
      <MatchNum>1</MatchNum>
      <ActionType>118</ActionType>
      <ActionSubType>1</ActionSubType>
      <sValue1>0123456789ABCDEF  D
ÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞß</sValue1>
      <sValue2>#</sValue2>
      <iValue3>-1</iValue3>
      <bValue1>FALSE</bValue1>
      <bValue2>FALSE</bValue2>
      <bValue3>FALSE</bValue3>
    </Command>
    <Command Name="E0-EF" Identifier="110" Enabled="TRUE">
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <OSD>FALSE</OSD>
      <Submatch>FALSE</Submatch>
      <Topmost>TRUE</Topmost>
      <OneMatch>FALSE</OneMatch>
      <UseVar>FALSE</UseVar>
      <MatchHidden>FALSE</MatchHidden>
      <MatchNum>1</MatchNum>
      <ActionType>118</ActionType>
      <ActionSubType>1</ActionSubType>
      <sValue1>0123456789ABCDEF  E
àáâãäåæçèéêëìíîï</sValue1>
      <sValue2>#</sValue2>
      <iValue3>-1</iValue3>
      <bValue1>FALSE</bValue1>
      <bValue2>FALSE</bValue2>
      <bValue3>FALSE</bValue3>
    </Command>
    <Command Name="F0-FF" Identifier="111" Enabled="TRUE">
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <OSD>FALSE</OSD>
      <Submatch>FALSE</Submatch>
      <Topmost>TRUE</Topmost>
      <OneMatch>FALSE</OneMatch>
      <UseVar>FALSE</UseVar>
      <MatchHidden>FALSE</MatchHidden>
      <MatchNum>1</MatchNum>
      <ActionType>118</ActionType>
      <ActionSubType>1</ActionSubType>
      <sValue1>0123456789ABCDEF  F
ðñòóôõö÷øùúûüýþÿ</sValue1>
      <sValue2>#</sValue2>
      <iValue3>-1</iValue3>
      <bValue1>FALSE</bValue1>
      <bValue2>FALSE</bValue2>
      <bValue3>FALSE</bValue3>
    </Command>
  </Group>
  <Group Name="Keypad" Identifier="112" Enabled="TRUE">
    <Comments>Test keypad events</Comments>
    <MultiGroup Name="Up" Identifier="113" Enabled="TRUE">
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <EventString Name="I" Identifier="114" Enabled="TRUE" Invert="FALSE" Device="118" IrStr="I"/>
      <Command Name="Display" Identifier="115" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x1F</sValue1>
        <sValue2>*</sValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="OSD" Identifier="116" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>4</ActionType>
        <ActionSubType>9</ActionSubType>
        <sValue1>Up</sValue1>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
    </MultiGroup>
    <MultiGroup Name="Down" Identifier="117" Enabled="TRUE">
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <EventString Name="J" Identifier="118" Enabled="TRUE" Invert="FALSE" Device="118" IrStr="J"/>
      <Command Name="Display" Identifier="119" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x1C</sValue1>
        <sValue2>*</sValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="OSD" Identifier="120" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>4</ActionType>
        <ActionSubType>9</ActionSubType>
        <sValue1>Down</sValue1>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
    </MultiGroup>
    <MultiGroup Name="Left" Identifier="121" Enabled="TRUE">
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <EventString Name="O" Identifier="122" Enabled="TRUE" Invert="FALSE" Device="118" IrStr="O"/>
      <Command Name="Display" Identifier="123" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x1E</sValue1>
        <sValue2>*</sValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="OSD" Identifier="124" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>4</ActionType>
        <ActionSubType>9</ActionSubType>
        <sValue1>Left</sValue1>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
    </MultiGroup>
    <MultiGroup Name="Right" Identifier="125" Enabled="TRUE">
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <EventString Name="E" Identifier="126" Enabled="TRUE" Invert="FALSE" Device="118" IrStr="E"/>
      <Command Name="Display" Identifier="127" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x1D</sValue1>
        <sValue2>*</sValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="OSD" Identifier="128" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>4</ActionType>
        <ActionSubType>9</ActionSubType>
        <sValue1>Right</sValue1>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
    </MultiGroup>
    <MultiGroup Name="Enter" Identifier="129" Enabled="TRUE">
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <EventString Name="H" Identifier="130" Enabled="TRUE" Invert="FALSE" Device="118" IrStr="H"/>
      <Command Name="Display" Identifier="131" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>0x9D</sValue1>
        <sValue2>*</sValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="OSD" Identifier="132" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>4</ActionType>
        <ActionSubType>9</ActionSubType>
        <sValue1>Enter</sValue1>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
    </MultiGroup>
    <MultiGroup Name="F2" Identifier="133" Enabled="TRUE">
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <EventString Name="M" Identifier="134" Enabled="TRUE" Invert="FALSE" Device="118" IrStr="M"/>
      <Command Name="Display" Identifier="135" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>F2</sValue1>
        <sValue2>s</sValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="OSD" Identifier="136" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>4</ActionType>
        <ActionSubType>9</ActionSubType>
        <sValue1>F2</sValue1>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
    </MultiGroup>
    <MultiGroup Name="F1" Identifier="137" Enabled="TRUE">
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <EventString Name="N" Identifier="138" Enabled="TRUE" Invert="FALSE" Device="118" IrStr="N"/>
      <Command Name="Display" Identifier="139" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>118</ActionType>
        <ActionSubType>1</ActionSubType>
        <sValue1>F1</sValue1>
        <sValue2>s</sValue2>
        <iValue3>-1</iValue3>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
      <Command Name="OSD" Identifier="140" Enabled="TRUE">
        <StateCount>1</StateCount>
        <StateBegin>1</StateBegin>
        <StateCurrent>1</StateCurrent>
        <StateInvert>FALSE</StateInvert>
        <OSD>FALSE</OSD>
        <Submatch>FALSE</Submatch>
        <Topmost>TRUE</Topmost>
        <OneMatch>FALSE</OneMatch>
        <UseVar>FALSE</UseVar>
        <MatchHidden>FALSE</MatchHidden>
        <MatchNum>1</MatchNum>
        <ActionType>4</ActionType>
        <ActionSubType>9</ActionSubType>
        <sValue1>F1</sValue1>
        <bValue1>FALSE</bValue1>
        <bValue2>FALSE</bValue2>
        <bValue3>FALSE</bValue3>
      </Command>
    </MultiGroup>
  </Group>
  <Group Name="Functions" Identifier="141" Enabled="TRUE">
    <Comments>Test LCD LUA extension functions</Comments>
    <Command Name="Script" Identifier="142" Enabled="TRUE">
      <Comments>Open in script editor</Comments>
      <StateCount>1</StateCount>
      <StateBegin>1</StateBegin>
      <StateCurrent>1</StateCurrent>
      <StateInvert>FALSE</StateInvert>
      <OSD>FALSE</OSD>
      <Submatch>FALSE</Submatch>
      <Topmost>TRUE</Topmost>
      <OneMatch>FALSE</OneMatch>
      <UseVar>FALSE</UseVar>
      <MatchHidden>FALSE</MatchHidden>
      <MatchNum>1</MatchNum>
      <ActionType>4</ActionType>
      <ActionSubType>34</ActionSubType>
      <sValue1>-- Reset display
LCD_Close()

-- Size
local w,h = LCD_Size()
print(w, h)

-- String
LCD_String(0, w / 2, 2, "**")

-- Custom characters
LCD_CustomCharacter(0, 0, "0b11111 0b10101 0b11101 0b10001 0b10001 0b11111")
LCD_CustomCharacter(0, w - 1, "0b11111 0b10101 0b10111 0b10001 0b10001 0b11111")
LCD_CustomCharacter(h - 1, 0, "0b11111 0b10001 0b10001 0b11101 0b10101 0b11111")
LCD_CustomCharacter(h - 1, w - 1, "0b11111 0b10001 0b10001 0b10111 0b10101 0b11111")
</sValue1>
      <bValue1>FALSE</bValue1>
      <bValue2>FALSE</bValue2>
      <bValue3>FALSE</bValue3>
    </Command>
  </Group>
</Girder>
